// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRestaurante.Context;

#nullable disable

namespace SistemaRestaurante.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250601170529_Models")]
    partial class Models
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaRestaurante.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistrada")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Estoques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataRegistrada = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            DataRegistrada = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            DataRegistrada = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            DataRegistrada = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            DataRegistrada = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Financeiro.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("Categoria")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Gastos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = (byte)1,
                            Data = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = (byte)0,
                            Data = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 220.75m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = (byte)1,
                            Data = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 98.50m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = (byte)1,
                            Data = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 3000.00m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = (byte)0,
                            Data = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 785.90m
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Financeiro.RegistroFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Agua")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DataRegistrada")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Estoque")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Funcionarios")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Gas")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Itens")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Luz")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("RegistrosFinanceiros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agua = 90m,
                            DataRegistrada = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estoque = 750m,
                            Funcionarios = 3000m,
                            Gas = 120m,
                            Itens = 250m,
                            Luz = 200m
                        },
                        new
                        {
                            Id = 2,
                            Agua = 95m,
                            DataRegistrada = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estoque = 800m,
                            Funcionarios = 3100m,
                            Gas = 130m,
                            Itens = 270m,
                            Luz = 210m
                        },
                        new
                        {
                            Id = 3,
                            Agua = 100m,
                            DataRegistrada = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estoque = 700m,
                            Funcionarios = 3200m,
                            Gas = 140m,
                            Itens = 260m,
                            Luz = 190m
                        },
                        new
                        {
                            Id = 4,
                            Agua = 85m,
                            DataRegistrada = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estoque = 780m,
                            Funcionarios = 3150m,
                            Gas = 125m,
                            Itens = 240m,
                            Luz = 205m
                        },
                        new
                        {
                            Id = 5,
                            Agua = 88m,
                            DataRegistrada = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estoque = 760m,
                            Funcionarios = 3300m,
                            Gas = 135m,
                            Itens = 265m,
                            Luz = 195m
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Itens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Refrigerante",
                            Valor = 5.50m
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Suco",
                            Valor = 12.00m
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Bolacha",
                            Valor = 8.00m
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Bala",
                            Valor = 2.20m
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Chicletes",
                            Valor = 1.00m
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Pasta de dente",
                            Valor = 15.00m
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstaPago")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Pessoa.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PontosFidelidade")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "12345678901",
                            DataNascimento = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ana Oliveira",
                            PontosFidelidade = 120,
                            Telefone = "(11) 91234-5678"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "23456789012",
                            DataNascimento = new DateTime(1985, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Bruno Souza",
                            PontosFidelidade = 200,
                            Telefone = "(21) 99876-5432"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "34567890123",
                            DataNascimento = new DateTime(1998, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Carla Lima",
                            PontosFidelidade = 80,
                            Telefone = "(31) 98765-4321"
                        },
                        new
                        {
                            Id = 4,
                            Cpf = "45678901234",
                            DataNascimento = new DateTime(1992, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Diego Martins",
                            PontosFidelidade = 150,
                            Telefone = "(41) 97654-3210"
                        },
                        new
                        {
                            Id = 5,
                            Cpf = "56789012345",
                            DataNascimento = new DateTime(1980, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Elaine Costa",
                            PontosFidelidade = 300,
                            Telefone = "(51) 96543-2109"
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Pessoa.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("Cargo")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = (byte)0,
                            Cpf = "535352123",
                            EstaAtivo = true,
                            Nome = "Paulo Tobias",
                            Salario = 3000m,
                            Senha = "senha123",
                            Status = 1,
                            Telefone = "4788845654"
                        },
                        new
                        {
                            Id = 2,
                            Cargo = (byte)3,
                            Cpf = "12345678900",
                            EstaAtivo = true,
                            Nome = "Joao Paulo",
                            Salario = 2500m,
                            Senha = "chimarrao@@!",
                            Status = 1,
                            Telefone = "413532535"
                        },
                        new
                        {
                            Id = 3,
                            Cargo = (byte)2,
                            Cpf = "7575422345",
                            EstaAtivo = true,
                            Nome = "Jeremias Antonio Junior",
                            Salario = 5680m,
                            Senha = "topzera224",
                            Status = 1,
                            Telefone = "242223254"
                        },
                        new
                        {
                            Id = 4,
                            Cargo = (byte)0,
                            Cpf = "7346895211",
                            EstaAtivo = true,
                            Nome = "Fernanda Albuquerque",
                            Salario = 7800m,
                            Senha = "senha123",
                            Status = 1,
                            Telefone = "5799568888"
                        },
                        new
                        {
                            Id = 5,
                            Cargo = (byte)1,
                            Cpf = "999067777",
                            EstaAtivo = true,
                            Nome = "Maria Betania",
                            Salario = 2900m,
                            Senha = "carambolas2323",
                            Status = 1,
                            Telefone = "4745454555"
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EstoqueId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QtdAtual")
                        .HasColumnType("int");

                    b.Property<int>("QtdMaxima")
                        .HasColumnType("int");

                    b.Property<int>("QtdMinima")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Arroz",
                            QtdAtual = 50,
                            QtdMaxima = 100,
                            QtdMinima = 10
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Feijão",
                            QtdAtual = 30,
                            QtdMaxima = 80,
                            QtdMinima = 15
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Macarrão",
                            QtdAtual = 25,
                            QtdMaxima = 70,
                            QtdMinima = 20
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Carne",
                            QtdAtual = 20,
                            QtdMaxima = 50,
                            QtdMinima = 5
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Óleo",
                            QtdAtual = 35,
                            QtdMaxima = 60,
                            QtdMinima = 8
                        });
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Item", b =>
                {
                    b.HasOne("SistemaRestaurante.Models.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Pedido", b =>
                {
                    b.HasOne("SistemaRestaurante.Models.Pessoa.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Produto", b =>
                {
                    b.HasOne("SistemaRestaurante.Models.Estoque", null)
                        .WithMany("Produtos")
                        .HasForeignKey("EstoqueId");
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Estoque", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SistemaRestaurante.Models.Pessoa.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
